
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  run-it-tests:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cypress/browsers:latest
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Install node modules"
          command: "npm install"
      - run:
          command: "node_modules/.bin/cypress run --browser chrome --headless --spec 'cypress/integration/integ/*.spec.js'"

  run-e2e-tests:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cypress/browsers:latest
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Install node modules"
          command: "npm install"
      - run:
          name: "Run e2e tests"
          command: "node_modules/.bin/cypress run --group it-tests --spec 'cypress/integration/e2e/*.spec.js'"


workflows:
  say-hello-workflow:
    jobs:
      - run-it-tests
